# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/appFolders.ui'
#
# Created: Thu Sep 16 13:44:02 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(680, 580)
        MainWindow.setProperty("Qt::WA_Maemo5AutoOrientation", True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.inpAddName = QtGui.QLineEdit(self.centralwidget)
        self.inpAddName.setReadOnly(True)
        self.inpAddName.setObjectName("inpAddName")
        self.horizontalLayout.addWidget(self.inpAddName)
        self.btnAddNameSelect = QtGui.QPushButton(self.centralwidget)
        self.btnAddNameSelect.setObjectName("btnAddNameSelect")
        self.horizontalLayout.addWidget(self.btnAddNameSelect)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listApps = QtGui.QListWidget(self.centralwidget)
        self.listApps.setObjectName("listApps")
        self.horizontalLayout_2.addWidget(self.listApps)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btnAppUp = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAppUp.sizePolicy().hasHeightForWidth())
        self.btnAppUp.setSizePolicy(sizePolicy)
        self.btnAppUp.setMinimumSize(QtCore.QSize(0, 0))
        self.btnAppUp.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnAppUp.setObjectName("btnAppUp")
        self.verticalLayout.addWidget(self.btnAppUp)
        self.btnAppDown = QtGui.QPushButton(self.centralwidget)
        self.btnAppDown.setMinimumSize(QtCore.QSize(0, 0))
        self.btnAppDown.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnAppDown.setObjectName("btnAppDown")
        self.verticalLayout.addWidget(self.btnAppDown)
        self.btnAppAdd = QtGui.QPushButton(self.centralwidget)
        self.btnAppAdd.setMinimumSize(QtCore.QSize(0, 0))
        self.btnAppAdd.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnAppAdd.setObjectName("btnAppAdd")
        self.verticalLayout.addWidget(self.btnAppAdd)
        self.btnAppDelete = QtGui.QPushButton(self.centralwidget)
        self.btnAppDelete.setMinimumSize(QtCore.QSize(0, 0))
        self.btnAppDelete.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btnAppDelete.setObjectName("btnAppDelete")
        self.verticalLayout.addWidget(self.btnAppDelete)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.btnUpdate = QtGui.QPushButton(self.centralwidget)
        self.btnUpdate.setObjectName("btnUpdate")
        self.verticalLayout.addWidget(self.btnUpdate)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 680, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuActionDiagnosis_Tool = QtGui.QMenu(self.menuBar)
        self.menuActionDiagnosis_Tool.setObjectName("menuActionDiagnosis_Tool")
        MainWindow.setMenuBar(self.menuBar)
        self.actionDiagnosis_Tool = QtGui.QAction(MainWindow)
        self.actionDiagnosis_Tool.setObjectName("actionDiagnosis_Tool")
        self.actionReadme = QtGui.QAction(MainWindow)
        self.actionReadme.setObjectName("actionReadme")
        self.actionActivate = QtGui.QAction(MainWindow)
        self.actionActivate.setObjectName("actionActivate")
        self.actionDeactivate = QtGui.QAction(MainWindow)
        self.actionDeactivate.setObjectName("actionDeactivate")
        self.actionFolders = QtGui.QAction(MainWindow)
        self.actionFolders.setObjectName("actionFolders")
        self.menuActionDiagnosis_Tool.addAction(self.actionDiagnosis_Tool)
        self.menuActionDiagnosis_Tool.addAction(self.actionReadme)
        self.menuActionDiagnosis_Tool.addAction(self.actionActivate)
        self.menuActionDiagnosis_Tool.addAction(self.actionDeactivate)
        self.menuActionDiagnosis_Tool.addAction(self.actionFolders)
        self.menuBar.addAction(self.menuActionDiagnosis_Tool.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ApMeFo - Hrw version", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddNameSelect.setText(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAppUp.setText(QtGui.QApplication.translate("MainWindow", "^", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAppDown.setText(QtGui.QApplication.translate("MainWindow", "v", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAppAdd.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAppDelete.setText(QtGui.QApplication.translate("MainWindow", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActionDiagnosis_Tool.setTitle(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDiagnosis_Tool.setText(QtGui.QApplication.translate("MainWindow", "Diagnosis Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReadme.setText(QtGui.QApplication.translate("MainWindow", "Readme", None, QtGui.QApplication.UnicodeUTF8))
        self.actionActivate.setText(QtGui.QApplication.translate("MainWindow", "Activate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeactivate.setText(QtGui.QApplication.translate("MainWindow", "Deactivate", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFolders.setText(QtGui.QApplication.translate("MainWindow", "Folders", None, QtGui.QApplication.UnicodeUTF8))

