# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/DataServer/FilesBen/Work/WIP/ApplicationMenuFolders/ui/appFolders.ui'
#
# Created: Tue Jun 29 16:42:45 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 818)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 781, 401))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget_4 = QtGui.QWidget(self.tab_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 20, 751, 301))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout_14 = QtGui.QGridLayout(self.layoutWidget_4)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem, 0, 1, 1, 1)
        self.btnActivate = QtGui.QPushButton(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnActivate.setFont(font)
        self.btnActivate.setObjectName("btnActivate")
        self.gridLayout_17.addWidget(self.btnActivate, 0, 3, 1, 1)
        self.btnDeactivate = QtGui.QPushButton(self.layoutWidget_4)
        self.btnDeactivate.setObjectName("btnDeactivate")
        self.gridLayout_17.addWidget(self.btnDeactivate, 0, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_17, 1, 0, 1, 1)
        self.txtWarning = QtGui.QTextBrowser(self.layoutWidget_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 117, 116))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 117, 116))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.txtWarning.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.txtWarning.setFont(font)
        self.txtWarning.setOpenExternalLinks(True)
        self.txtWarning.setObjectName("txtWarning")
        self.gridLayout_14.addWidget(self.txtWarning, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tabCreate = QtGui.QWidget()
        self.tabCreate.setObjectName("tabCreate")
        self.layoutWidget = QtGui.QWidget(self.tabCreate)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 751, 301))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.btnEditNameSelect = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnEditNameSelect.setFont(font)
        self.btnEditNameSelect.setObjectName("btnEditNameSelect")
        self.gridLayout_9.addWidget(self.btnEditNameSelect, 0, 1, 1, 1)
        self.inpEditName = QtGui.QLineEdit(self.layoutWidget)
        self.inpEditName.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.inpEditName.setFont(font)
        self.inpEditName.setObjectName("inpEditName")
        self.gridLayout_9.addWidget(self.inpEditName, 0, 0, 1, 1)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.gridLayout_9)
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btnIconSelect = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnIconSelect.setFont(font)
        self.btnIconSelect.setObjectName("btnIconSelect")
        self.gridLayout.addWidget(self.btnIconSelect, 0, 1, 1, 1)
        self.inpIcon = QtGui.QLineEdit(self.layoutWidget)
        self.inpIcon.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.inpIcon.setFont(font)
        self.inpIcon.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase)
        self.inpIcon.setObjectName("inpIcon")
        self.gridLayout.addWidget(self.inpIcon, 0, 0, 1, 1)
        self.formLayout.setLayout(3, QtGui.QFormLayout.FieldRole, self.gridLayout)
        self.gridLayout_3.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 0, 1, 1)
        self.btnCreate = QtGui.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnCreate.setFont(font)
        self.btnCreate.setObjectName("btnCreate")
        self.gridLayout_2.addWidget(self.btnCreate, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabCreate, "")
        self.tabDelete = QtGui.QWidget()
        self.tabDelete.setObjectName("tabDelete")
        self.layoutWidget_2 = QtGui.QWidget(self.tabDelete)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 751, 301))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtGui.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btnDelNameSelect = QtGui.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnDelNameSelect.setFont(font)
        self.btnDelNameSelect.setObjectName("btnDelNameSelect")
        self.gridLayout_5.addWidget(self.btnDelNameSelect, 0, 1, 1, 1)
        self.inpDelName = QtGui.QLineEdit(self.layoutWidget_2)
        self.inpDelName.setEnabled(False)
        self.inpDelName.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.inpDelName.setFont(font)
        self.inpDelName.setObjectName("inpDelName")
        self.gridLayout_5.addWidget(self.inpDelName, 0, 0, 1, 1)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.FieldRole, self.gridLayout_5)
        self.gridLayout_4.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 0, 0, 1, 1)
        self.btnDelete = QtGui.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnDelete.setFont(font)
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout_8.addWidget(self.btnDelete, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tabDelete, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget_3 = QtGui.QWidget(self.tab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 20, 751, 301))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_10 = QtGui.QGridLayout(self.layoutWidget_3)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.btnAppAdd = QtGui.QPushButton(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAppAdd.sizePolicy().hasHeightForWidth())
        self.btnAppAdd.setSizePolicy(sizePolicy)
        self.btnAppAdd.setMinimumSize(QtCore.QSize(35, 35))
        self.btnAppAdd.setMaximumSize(QtCore.QSize(50, 50))
        self.btnAppAdd.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btnAppAdd.setFont(font)
        self.btnAppAdd.setObjectName("btnAppAdd")
        self.gridLayout_13.addWidget(self.btnAppAdd, 0, 1, 1, 1)
        self.btnAppDelete = QtGui.QPushButton(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAppDelete.sizePolicy().hasHeightForWidth())
        self.btnAppDelete.setSizePolicy(sizePolicy)
        self.btnAppDelete.setMinimumSize(QtCore.QSize(35, 35))
        self.btnAppDelete.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btnAppDelete.setFont(font)
        self.btnAppDelete.setObjectName("btnAppDelete")
        self.gridLayout_13.addWidget(self.btnAppDelete, 1, 1, 1, 1)
        self.btnAppUp = QtGui.QPushButton(self.layoutWidget_3)
        self.btnAppUp.setMinimumSize(QtCore.QSize(35, 35))
        self.btnAppUp.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.btnAppUp.setFont(font)
        self.btnAppUp.setObjectName("btnAppUp")
        self.gridLayout_13.addWidget(self.btnAppUp, 0, 0, 1, 1)
        self.btnAppDown = QtGui.QPushButton(self.layoutWidget_3)
        self.btnAppDown.setMinimumSize(QtCore.QSize(35, 35))
        self.btnAppDown.setMaximumSize(QtCore.QSize(50, 50))
        self.btnAppDown.setObjectName("btnAppDown")
        self.gridLayout_13.addWidget(self.btnAppDown, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_13)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.btnUpdate = QtGui.QPushButton(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUpdate.sizePolicy().hasHeightForWidth())
        self.btnUpdate.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnUpdate.setFont(font)
        self.btnUpdate.setObjectName("btnUpdate")
        self.verticalLayout_2.addWidget(self.btnUpdate)
        self.gridLayout_12.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.listApps = QtGui.QListWidget(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listApps.sizePolicy().hasHeightForWidth())
        self.listApps.setSizePolicy(sizePolicy)
        self.listApps.setMinimumSize(QtCore.QSize(0, 230))
        self.listApps.setObjectName("listApps")
        self.gridLayout_12.addWidget(self.listApps, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_12, 1, 0, 1, 1)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_4 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.btnAddNameSelect = QtGui.QPushButton(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnAddNameSelect.setFont(font)
        self.btnAddNameSelect.setObjectName("btnAddNameSelect")
        self.gridLayout_11.addWidget(self.btnAddNameSelect, 0, 1, 1, 1)
        self.inpAddName = QtGui.QLineEdit(self.layoutWidget_3)
        self.inpAddName.setEnabled(False)
        self.inpAddName.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.inpAddName.setFont(font)
        self.inpAddName.setObjectName("inpAddName")
        self.gridLayout_11.addWidget(self.inpAddName, 0, 0, 1, 1)
        self.formLayout_3.setLayout(2, QtGui.QFormLayout.FieldRole, self.gridLayout_11)
        self.gridLayout_10.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.layoutWidget1 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.layoutWidget2 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_7 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuApMeFo_Menu = QtGui.QMenu(self.menuBar)
        self.menuApMeFo_Menu.setObjectName("menuApMeFo_Menu")
        MainWindow.setMenuBar(self.menuBar)
        self.actionDiagnosis_Tool = QtGui.QAction(MainWindow)
        self.actionDiagnosis_Tool.setObjectName("actionDiagnosis_Tool")
        self.actionReadme = QtGui.QAction(MainWindow)
        self.actionReadme.setObjectName("actionReadme")
        self.menuApMeFo_Menu.addAction(self.actionDiagnosis_Tool)
        self.menuApMeFo_Menu.addAction(self.actionReadme)
        self.menuBar.addAction(self.menuApMeFo_Menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "ApMeFo", None, QtGui.QApplication.UnicodeUTF8))
        self.btnActivate.setText(QtGui.QApplication.translate("MainWindow", "Activate", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDeactivate.setText(QtGui.QApplication.translate("MainWindow", "Deactivate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "(De-)Activate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Folder Name", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEditNameSelect.setText(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Folder Icon", None, QtGui.QApplication.UnicodeUTF8))
        self.btnIconSelect.setText(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCreate.setText(QtGui.QApplication.translate("MainWindow", "Create/Edit Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCreate), QtGui.QApplication.translate("MainWindow", "Create/Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Folder Name", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDelNameSelect.setText(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDelete.setText(QtGui.QApplication.translate("MainWindow", "Delete Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDelete), QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAppAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAppDelete.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAppUp.setText(QtGui.QApplication.translate("MainWindow", "^", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAppDown.setText(QtGui.QApplication.translate("MainWindow", "v", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Folder Name", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddNameSelect.setText(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Add Apps", None, QtGui.QApplication.UnicodeUTF8))
        self.menuApMeFo_Menu.setTitle(QtGui.QApplication.translate("MainWindow", "ApMeFo Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDiagnosis_Tool.setText(QtGui.QApplication.translate("MainWindow", "Diagnosis Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReadme.setText(QtGui.QApplication.translate("MainWindow", "Readme", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

