# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appFolders.ui'
#
# Created: Wed Sep  8 20:47:26 2010
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(656, 420)
        MainWindow.setProperty("Qt::WA_Maemo5AutoOrientation", True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.txtWarning = QtGui.QTextBrowser(self.tab_2)
        self.txtWarning.setObjectName("txtWarning")
        self.verticalLayout.addWidget(self.txtWarning)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnDeactivate = QtGui.QPushButton(self.tab_2)
        self.btnDeactivate.setObjectName("btnDeactivate")
        self.horizontalLayout.addWidget(self.btnDeactivate)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnActivate = QtGui.QPushButton(self.tab_2)
        self.btnActivate.setObjectName("btnActivate")
        self.horizontalLayout.addWidget(self.btnActivate)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tabCreate = QtGui.QWidget()
        self.tabCreate.setObjectName("tabCreate")
        self.gridLayout_3 = QtGui.QGridLayout(self.tabCreate)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.tabCreate)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.inpEditName = QtGui.QLineEdit(self.tabCreate)
        self.inpEditName.setObjectName("inpEditName")
        self.horizontalLayout_2.addWidget(self.inpEditName)
        self.btnEditNameSelect = QtGui.QPushButton(self.tabCreate)
        self.btnEditNameSelect.setObjectName("btnEditNameSelect")
        self.horizontalLayout_2.addWidget(self.btnEditNameSelect)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtGui.QLabel(self.tabCreate)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.inpIcon = QtGui.QLineEdit(self.tabCreate)
        self.inpIcon.setObjectName("inpIcon")
        self.horizontalLayout_3.addWidget(self.inpIcon)
        self.btnIconSelect = QtGui.QPushButton(self.tabCreate)
        self.btnIconSelect.setObjectName("btnIconSelect")
        self.horizontalLayout_3.addWidget(self.btnIconSelect)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btnDelete = QtGui.QPushButton(self.tabCreate)
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout_4.addWidget(self.btnDelete)
        self.btnCreate = QtGui.QPushButton(self.tabCreate)
        self.btnCreate.setObjectName("btnCreate")
        self.horizontalLayout_4.addWidget(self.btnCreate)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabCreate, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.inpAddName = QtGui.QLineEdit(self.tab)
        self.inpAddName.setObjectName("inpAddName")
        self.horizontalLayout_7.addWidget(self.inpAddName)
        self.btnAddNameSelect = QtGui.QPushButton(self.tab)
        self.btnAddNameSelect.setObjectName("btnAddNameSelect")
        self.horizontalLayout_7.addWidget(self.btnAddNameSelect)
        self.gridLayout_6.addLayout(self.horizontalLayout_7, 0, 0, 1, 2)
        self.listApps = QtGui.QListWidget(self.tab)
        self.listApps.setObjectName("listApps")
        self.gridLayout_6.addWidget(self.listApps, 1, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.btnAppUp = QtGui.QPushButton(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAppUp.sizePolicy().hasHeightForWidth())
        self.btnAppUp.setSizePolicy(sizePolicy)
        self.btnAppUp.setMinimumSize(QtCore.QSize(35, 35))
        self.btnAppUp.setMaximumSize(QtCore.QSize(50, 50))
        self.btnAppUp.setObjectName("btnAppUp")
        self.gridLayout_5.addWidget(self.btnAppUp, 0, 0, 1, 1)
        self.btnAppAdd = QtGui.QPushButton(self.tab)
        self.btnAppAdd.setMinimumSize(QtCore.QSize(35, 35))
        self.btnAppAdd.setMaximumSize(QtCore.QSize(50, 50))
        self.btnAppAdd.setObjectName("btnAppAdd")
        self.gridLayout_5.addWidget(self.btnAppAdd, 0, 1, 1, 1)
        self.btnAppDown = QtGui.QPushButton(self.tab)
        self.btnAppDown.setMinimumSize(QtCore.QSize(35, 35))
        self.btnAppDown.setMaximumSize(QtCore.QSize(50, 50))
        self.btnAppDown.setObjectName("btnAppDown")
        self.gridLayout_5.addWidget(self.btnAppDown, 1, 0, 1, 1)
        self.btnAppDelete = QtGui.QPushButton(self.tab)
        self.btnAppDelete.setMinimumSize(QtCore.QSize(35, 35))
        self.btnAppDelete.setMaximumSize(QtCore.QSize(50, 50))
        self.btnAppDelete.setObjectName("btnAppDelete")
        self.gridLayout_5.addWidget(self.btnAppDelete, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.btnUpdate = QtGui.QPushButton(self.tab)
        self.btnUpdate.setObjectName("btnUpdate")
        self.verticalLayout_2.addWidget(self.btnUpdate)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 656, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuActionDiagnosis_Tool = QtGui.QMenu(self.menuBar)
        self.menuActionDiagnosis_Tool.setObjectName("menuActionDiagnosis_Tool")
        MainWindow.setMenuBar(self.menuBar)
        self.actionDiagnosis_Tool = QtGui.QAction(MainWindow)
        self.actionDiagnosis_Tool.setObjectName("actionDiagnosis_Tool")
        self.actionReadme = QtGui.QAction(MainWindow)
        self.actionReadme.setObjectName("actionReadme")
        self.menuActionDiagnosis_Tool.addAction(self.actionDiagnosis_Tool)
        self.menuActionDiagnosis_Tool.addAction(self.actionReadme)
        self.menuBar.addAction(self.menuActionDiagnosis_Tool.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDeactivate.setText(QtGui.QApplication.translate("MainWindow", "Deactivate", None, QtGui.QApplication.UnicodeUTF8))
        self.btnActivate.setText(QtGui.QApplication.translate("MainWindow", "Activate", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "(De-)Activate", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEditNameSelect.setText(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Icon", None, QtGui.QApplication.UnicodeUTF8))
        self.btnIconSelect.setText(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDelete.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCreate.setText(QtGui.QApplication.translate("MainWindow", "Create/Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCreate), QtGui.QApplication.translate("MainWindow", "Folders", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Folder name", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddNameSelect.setText(QtGui.QApplication.translate("MainWindow", "Select", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAppUp.setText(QtGui.QApplication.translate("MainWindow", "^", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAppAdd.setText(QtGui.QApplication.translate("MainWindow", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAppDown.setText(QtGui.QApplication.translate("MainWindow", "v", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAppDelete.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUpdate.setText(QtGui.QApplication.translate("MainWindow", "Update", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Add apps", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActionDiagnosis_Tool.setTitle(QtGui.QApplication.translate("MainWindow", "actionDiagnosis_Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDiagnosis_Tool.setText(QtGui.QApplication.translate("MainWindow", "Diagnosis_Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.actionReadme.setText(QtGui.QApplication.translate("MainWindow", "Readme", None, QtGui.QApplication.UnicodeUTF8))

